x-service: &service
  image: image: public.ecr.aws/firetiger/firetiger:latest
  volumes:
  - storage:/mnt/storage
  environment: &environment
  - FT_BUCKET=http://firetiger-storage-server:4317
  - FT_CATALOG=http://firetiger-catalog-server:4317
  - FT_NAMESPACE=firetiger.docker.compose
  - FT_LOG_FORMAT=cli
  - GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore  # https://protobuf.dev/reference/go/faq/#namespace-conflict
  - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
  healthcheck:
    test: curl -f http://localhost:4317/ready
    interval: 10s
    timeout: 3s
    retries: 3
    start_period: 5s
  restart: always

services:
  firetiger-api-gateway:
    image: traefik:v2.10
    command:
    - "--accesslog=true"
    - "--api.insecure=true"
    - "--log.level=INFO"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    - "--providers.file.directory=/etc/traefik/dynamic"
    - "--entrypoints.web.address=:80"
    - "--ping=true"
    ports:
    - 4317:80
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./docker-traefik.yaml:/etc/traefik/dynamic/routes.yml:ro
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ping
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  firetiger-logs-ingest-server:
    <<: *service
    command: run ingest server

  firetiger-metrics-ingest-server:
    <<: *service
    command: run ingest server

  firetiger-traces-ingest-server:
    <<: *service
    command: run ingest server

  firetiger-logs-ingest-worker:
    <<: *service
    command: run ingest worker --create --table=logs

  firetiger-metrics-ingest-worker:
    <<: *service
    command: run ingest worker --create --table=metrics

  firetiger-traces-ingest-worker:
    <<: *service
    command: run ingest worker --create --table=traces

  firetiger-query-server:
    <<: *service
    command: run query server

  firetiger-catalog-server:
    <<: *service
    command: |-
      run catalog server
      --catalog-backend=sqlite3:///mnt/storage/catalog.sqlite?cache=shared
      --catalog-frontend=http://localhost:4317/catalog
      --storage-backend=http://firetiger-storage-server:4317
      --storage-frontend=http://localhost:4317/storage
    volumes:
    - storage:/mnt/storage

  firetiger-storage-server:
    <<: *service
    command: |-
      run storage server
      --bucket=file:///mnt/storage
      --storage-backend=http://firetiger-storage-server:4317
      --storage-frontend=http://localhost:4317/storage
    volumes:
    - storage:/mnt/storage

  grafana:
    image: grafana/grafana:latest
    ports:
    - 8321:3000
    environment:
    - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_DATAPROXY_TIMEOUT=60
    - GF_DATABASE_TYPE=sqlite3
    - GF_DATABASE_PATH=/var/lib/grafana/grafana.db
    volumes:
    - grafana:/var/lib/grafana
    - ./docker-grafana.yaml:/etc/grafana/provisioning/datasources/ds.yaml:ro

  # https://opentelemetry.io/docs/collector/installation/
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4319:4317 # OTLP gRPC receiver  # Modified host port so it doesn't conflict
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extensio

volumes:
  grafana:
  storage:
